package:
    name: exdir-cli
    version: {{ environ.get("GIT_TAG", "0.0.0_custom")|replace("v", "")|replace("-", "_") }}
source:
    git_url: ..
build:
    script: python setup.py install
    
entry_points:
  - exdir=exdircli.main:main
    
requirements:
    build:
        - future
    run:
        - future
        - python
        - exdir
test:
  script:
    exdir --help
about:
    description: ''
    dev_url: https://github.com/CINPLA/exdir-cli
    license: GNU GPLv3
    license_family: GPL
    license_file: LICENSE
extra:
    recipe-maintainers:
        - dragly
